# Generated by Django 4.2.1 on 2023-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Dermaskill', max_length=100),
        ),
    ]
